fixed of the new configure options. added more debug prints

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19272,6 +19272,85 @@ else
   USE_SDL_FALSE=
 fi
 
+if test $SELECTED_LOWLIB = sdl; then
+	echo "$as_me:$LINENO: checking for SDL_Init in -lSDL" >&5
+echo $ECHO_N "checking for SDL_Init in -lSDL... $ECHO_C" >&6
+if test "${ac_cv_lib_SDL_SDL_Init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lSDL  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char SDL_Init ();
+int
+main ()
+{
+SDL_Init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_SDL_SDL_Init=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_SDL_SDL_Init=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_SDL_SDL_Init" >&5
+echo "${ECHO_T}$ac_cv_lib_SDL_SDL_Init" >&6
+if test $ac_cv_lib_SDL_SDL_Init = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define USE_SDL 1
+_ACEOF
+ LIBS="$LIBS $(sdl-config --libs)" NEUROFLAGS="$NEUROFLAGS $SDLFLAGS"
+else
+  { { echo "$as_me:$LINENO: error: You don't have libSDL" >&5
+echo "$as_me: error: You don't have libSDL" >&2;}
+   { (exit you can get it from http://www.libsdl.org); exit you can get it from http://www.libsdl.org; }; }
+fi
+
+
+fi
+
 
 # need to make it so if it is set to 0, it will still compile :D
 #AC_ARG_ENABLE(libSDL,
