made quite some work, most notably is the implementation of fonts in x11(sdl one still to do), a lot of commenting work and did interface functions (not all however) for the Lib_ functions.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -23092,7 +23092,85 @@ echo "$as_me: error: You don't have libXpm" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
+
+	freetype_enable=yes
+
 	cp include/extlib.h include/neuro
+fi
+
+if test $freetype_enable = xyes; then
+	echo "$as_me:$LINENO: checking for FT_New_Face in -lfreetype" >&5
+echo $ECHO_N "checking for FT_New_Face in -lfreetype... $ECHO_C" >&6
+if test "${ac_cv_lib_freetype_FT_New_Face+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lfreetype  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char FT_New_Face ();
+int
+main ()
+{
+FT_New_Face ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_freetype_FT_New_Face=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_freetype_FT_New_Face=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_freetype_FT_New_Face" >&5
+echo "${ECHO_T}$ac_cv_lib_freetype_FT_New_Face" >&6
+if test $ac_cv_lib_freetype_FT_New_Face = yes; then
+  LIBS="$LIBS `freetype-config --libs`" CFLAGS="$CFLAGS `freetype-config --cflags`"
+else
+  { { echo "$as_me:$LINENO: error: You don't have the libfreetype2 library you can get it from freetype.sourceforge.net" >&5
+echo "$as_me: error: You don't have the libfreetype2 library you can get it from freetype.sourceforge.net" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 fi
 
 
